on:
  - pull_request
  - push

name: "Windows"

jobs:

  windows:
    name: "Tests (Windows)"

    defaults:
      run:
        shell: cmd

    runs-on: windows-2022

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "phpinfo"
        run: php -i
